# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

# Default values for apsviz thredds.
# This is a YAML-formatted file.

# replicaCount: 1

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/0,::/0"
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '86400'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '86400'
    nginx.ingress.kubernetes.io/send-timeout: '86400'
    nginx.ingress.kubernetes.io/service-upstream: 'true'
    nginx.ingress.kubernetes.io/upstream-keepalive-timeout: '86400'
    nginx.ingress.kubernetes.io/connection-proxy-header: "keep-alive"
  host: tdsres.apps.renci.org
  pathType: "ImplementationSpecific"
  endpoints:
    - /favicon.ico
    - /thredds
    - /manager
  tls:
    enabled: true

resources:
  limits:
    ephemeral-storage: 512Mi

configMapName: "apsviz-thredds-res-scripts"

nfsVolumes:
  nfs-3:
    name: "nfs-3"
    mountPath: "/projects/ees"
    path: "/projects/ees"
    server: "isilon.edc.renci.org"

configMaps:
  item-1:
    mountPath: "/content/thredds/"
    subPath: "CHEER.xml"

  item-2:
    mountPath: "/content/thredds/"
    subPath: "DataLayers.xml"

  item-3:
    mountPath: "/content/thredds/"
    subPath: "Reanalysis.xml"

  item-4:
    mountPath: "/content/thredds/"
    subPath: "Taylor.xml"

  item-5:
    mountPath: "/content/thredds/"
    subPath: "aps2023.xml"

  item-6:
    mountPath: "/content/thredds/"
    subPath: "catalog.xml"

  item-7:
    mountPath: "/content/thredds/"
    subPath: "enhancedCatalog.xml"

  item-8:
    mountPath: "/content/thredds/"
    subPath: "threddsConfig.xml"

  item-9:
    mountPath: "/content/thredds/"
    subPath: "wmsConfig.xml"

  item-10:
    mountPath: "/content/thredds/"
    subPath: "Users.xml"
