# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

# Default values for apsviz thredds.
# This is a YAML-formatted file.

replicaCount: 1

ingress:
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: null

  host: tdsres.apps.renci.org

configMapName: "apsviz-thredds-res-scripts"

configMaps:
  item-1:
    mountPath: "/content/thredds/"
    subPath: "CHEER.xml"

  item-2:
    mountPath: "/content/thredds/"
    subPath: "DataLayers.xml"

  item-3:
    mountPath: "/content/thredds/"
    subPath: "Reanalysis.xml"

  item-4:
    mountPath: "/content/thredds/"
    subPath: "Taylor.xml"

  item-5:
    mountPath: "/content/thredds/"
    subPath: "aps2023.xml"

  item-6:
    mountPath: "/content/thredds/"
    subPath: "catalog.xml"

  item-7:
    mountPath: "/content/thredds/"
    subPath: "enhancedCatalog.xml"

  item-8:
    mountPath: "/content/thredds/"
    subPath: "threddsConfig.xml"

  item-9:
    mountPath: "/content/thredds/"
    subPath: "wmsConfig.xml"
