# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

# Default values for apsviz thredds.
# This is a YAML-formatted file.

replicaCount: 1

podSecurityContext:
  fsGroup: 30000

image:
  repository: containers.renci.org/eds/apsviz-thredds
  tag: latest
  pullPolicy: Always

logVolumes:
  create: true
  name: apsviz-thredds-logs-vol
  claimName: apsviz-thredds-log-pvc
  storageClass: "sc"
  size: 2Gi
  accessMode: "ReadWriteMany"
  efsHandle: "fs"
  mountPoint: /home/nru/tomcat/logs

nfsVolumes:
  nfs-1:
    name: "nfs-1"
    mountPath: "/projects/ncfs/opendap/data"
    path: "/ncfs/opendap/data"
    server: "na-projects.edc.renci.org"

  nfs-2:
    name: "nfs-2"
    mountPath: "/projects/reanalysis"
    path: "/reanalysis"
    server: "na-projects.edc.renci.org"

securityContext:
  runAsUser: 30000
  supplementalGroups:
   - 1078
   - 1170

tomcatCatalinaHome: "/home/nru/tomcat"

tomcat-users:
  user-1:
    name: "name1"
    password: "testpw1"
    roles: "role1"
  user-2:
    name: "name2"
    password: "testpw2"
    roles: "role2,role3"

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '86400'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '86400'
    nginx.ingress.kubernetes.io/send-timeout: '86400'
    nginx.ingress.kubernetes.io/service-upstream: 'true'
    nginx.ingress.kubernetes.io/upstream-keepalive-timeout: '86400'
    nginx.ingress.kubernetes.io/connection-proxy-header: "keep-alive"
  host: teststd-dev.apps.renci.org
  pathType: "ImplementationSpecific"
  endpoints:
    - /favicon.ico
    - /thredds
    - /manager
  tls:
    enabled: true
