apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "asgs-postgres.fullname" . }}-backup-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  {{ if .Values.isAWS }}
  storageClassName: {{ .Values.storage.class }}
  {{ end }}

  resources:
    requests:
      storage: {{ .Values.storage.size }}