apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "asgs-postgres.fullname" . }}-backup-pvc"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}