{{ if .Values.dataUrl }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{- include "asgs-postgres.fullname" . }}-postgres-job"
spec:
  template:
    metadata:
      name: "{{- include "asgs-postgres.fullname" . }}-postgres-job"
    spec:
      initContainers:
        - name: download-bckp
          image: busybox
          command:
            - 'wget'
          args:
            - '-O'
            - '/data/dump.sql'
            - '{{ .Values.dataUrl }}'
          volumeMounts:
          - name: data-dir
            mountPath: '/data/'
      containers:
      - name: loader-container
        image: "{{ .Values.image.repository}}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /loaddb.sh
        env:
        - name: PGHOST
          value: {{ include "asgs-postgres.fullname" . }}
        - name: PGPORT
          value: "{{ .Values.service.port }}"
        - name: PGUSER
          value: {{ .Values.adminuser }}
        - name: PGPASSWORD
          value: {{ .Values.adminpassword }}
        volumeMounts:
        - mountPath:  loaddb.sh
          name: "loader-script"
          subPath: "loaddb.sh"
        - mountPath: /data
          name: "data-dir"       
      restartPolicy: OnFailure
      volumes:
      - name: loader-script
        configMap:
          name: "{{- include "asgs-postgres.fullname" . }}-scripts"
          defaultMode: 0777
      - name: data-dir
        persistentVolumeClaim:
          claimName: "{{ include "asgs-postgres.fullname" . }}-backup-pvc"
  {{ end }}