apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{- include "asgs-postgres.fullname" . }}-scripts"
data:
  loaddb.sh: |-
    #!/bin/bash    
    BCKP_FILE=/data/dump.sql
    until pg_isready ; do
        echo "postgres not ready";
        sleep 10
    done

    # note the backup should be created on the server using the following commanmd line:
    # pg_dumpall > /projects/stars/var/data_services/asgs_pg_all.dump

    psql -U {{ .Values.adminuser }} < /data/dump.sql

