apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{- include "asgs-postgres.fullname" . }}-scripts"
data:
  loaddb.sh: |-
    #!/bin/bash    
    BCKP_FILE=/data/dump.sql
    until pg_isready ; do
        echo "postgres not ready";
        sleep 10
    done
    pg_restore -j 4 -d asgs_dashboard $BCKP_FILE
