---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "apsviz-timeseriesdb.fullname" . }}-db
  labels:
    {{- include "apsviz-timeseriesdb.labels" . | nindent 4 }}
    type: dbms
spec:
  replicas: 1
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "apsviz-timeseriesdb.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: timescale/timescaledb-postgis:latest-pg13
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: POSTGRES_DB
            value: "{{ .Values.postgres.database }}"
          - name: POSTGRES_USER
            value: "{{ .Values.postgres.username }}"
          - name: POSTGRES_PASSWORD
            value: "{{ .Values.postgres.password }}"

          ports:
            - name: postgres-port
              containerPort: {{ .Values.postgres.port }}
              protocol: TCP

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-data
          - mountPath: /home/DataIngesting
            name: ingest-data
          {{- if .Values.shmSize }}
          - mountPath: /dev/shm
            name: dshm
          {{- end }}
      restartPolicy: Always
      volumes:
        {{- if .Values.shmSize }}
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.shmSize }}
        {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "apsviz-timeseriesdb.fullname" . }}-postgres-data
      spec:
        accessModes: [ {{ .Values.accessMode }} ]
        {{ if .Values.isAWS }}
        storageClassName: {{ .Values.storage.class }}
        {{ end }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
