# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2024 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apsviz-ui-data.fullname" . }}
  labels:
    {{- include "apsviz-ui-data.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http }}
      targetPort: {{ .Values.service.target_port }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.https }}
      targetPort: {{ .Values.service.target_port }}
      protocol: TCP
      name: https
  selector:
    {{- include "apsviz-ui-data.selectorLabels" . | nindent 4 }}
