# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

apiVersion: v2
name: geoserver
version: 0.3.1
appVersion: 2.20.1
description: Chart for GeoServer
keywords:
  - GeoServer
  - GIS
home: http://geoserver.org
sources:
  - https://github.com/geoserver/geoserver
maintainers:
  - name: lucernae
    email: lana.pcfre@gmail.com
engine: gotpl
icon: https://raw.githubusercontent.com/kartoza/charts/master/assets/logo/GeoServer_500.png
