# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

# Default values for asgs-rabbitmq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: containers.renci.org/eds/asgs-rabbitmq
  tag: latest
  pullPolicy: "IfNotPresent"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

storage:
  size: 5Gi

isAWS: false

secrets:
  queuePort: 1234
  webPort: 2345
  queueUser: "someuser"
  queuePassword: "somepassword"
  queueAdminPassword: "someadminpassword"

podAnnotations: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  http: 80
  https: 443
  target_port: 15672

ingress:
  enabled: false
  class: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/connection-proxy-header: "keep-alive"
    nginx.ingress.kubernetes.io/send-timeout: "86400"
    nginx.ingress.kubernetes.io/service-upstream: 'true'
    nginx.ingress.kubernetes.io/upstream-keepalive-timeout: "86400"
  host: somehost
  pathType: "ImplementationSpecific"
  tls:
    enabled: false

networking:
  enabled: false
  type: "sometype"
  loadbalancerIP:
  name: "somename"
  port: 1234
  protocol: "someprotocol"
  host: "somehost"

resources:
  limits:
    memory: 512Mi
    ephemeral-storage: 64Mi
    cpu: 500m
  requests:
    memory: 256Mi
    ephemeral-storage: 50Mi
    cpu: 200m

nodeSelector: {}

tolerations: []

affinity: {}
