apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{- include "apsviz-archiver.fullname" . }}-scripts"
data:
  rule_file.json: |-
    {
      "rule_definition_name": "APSViz archival rules",
      "rule_definition_version": "0.0.0",
      "description": "Log directory operations.",
      "rule_sets":
      [
        {
          "rule_set_name": "Log operations rule set using the by age criteria",
          "description": "Copy /data/logs/ -> /data/tmp/archiver-test/, copy archiver-test/ -> ./copy/, move copy/ -> ../move/, remove move/",
          "rules": [
            {
              "name": "Copy log directories",
              "description": "This rule copies directories of a certain age from source to destination.",
              "query_criteria_type": "BY_AGE",
              "query_data_type": "INTEGER",
              "query_data_value": 7,
              "predicate_type": "GREATER_THAN_OR_EQUAL_TO",
              "action_type": "SWEEP_COPY",
              "data_type": "DIRECTORY",
              "source": "/data/logs",
              "destination": "/data/tmp/archiver-test"
            },
            {
              "name": "Copy log directories again to new location",
              "description": "This rule copies directories of a certain age from source to destination.",
              "query_criteria_type": "BY_AGE",
              "query_data_type": "INTEGER",
              "query_data_value": 1,
              "predicate_type": "GREATER_THAN_OR_EQUAL_TO",
              "action_type": "SWEEP_COPY",
              "data_type": "DIRECTORY",
              "source": "/data/tmp/archiver-test",
              "destination": "/data/tmp/archiver-test/copy"
            },
            {
              "name": "Move log directories",
              "description": "This rule moves directories of a certain age from source to destination.",
              "query_criteria_type": "BY_AGE",
              "query_data_type": "INTEGER",
              "query_data_value": 1,
              "predicate_type": "GREATER_THAN_OR_EQUAL_TO",
              "action_type": "SWEEP_MOVE",
              "data_type": "DIRECTORY",
              "source": "/data/tmp/archiver-test/copy",
              "destination": "/data/tmp/archiver-test/move"
            },
            {
              "name": "Remove log directories",
              "description": "This rule removes directories of a certain age.",
              "query_criteria_type": "BY_AGE",
              "query_data_type": "INTEGER",
              "query_data_value": 3,
              "predicate_type": "GREATER_THAN_OR_EQUAL_TO",
              "action_type": "SWEEP_REMOVE",
              "data_type": "DIRECTORY",
              "source": "/data/tmp/archiver-test/move",
              "destination": null
            }
          ]
        },
        {
          "rule_set_name": "Archive rule set for AST harvester data.",
          "description": "Copy /data/ast-run-harvester files -> /data/tmp/ast-run-harvester",
          "rules": [
            {
              "name": "Copy AST harvester data directory",
              "description": "This rule copies files of a certain age from source to destination.",
              "query_criteria_type": "BY_AGE",
              "query_data_type": "INTEGER",
              "query_data_value": 7,
              "predicate_type": "GREATER_THAN_OR_EQUAL_TO",
              "action_type": "SWEEP_COPY",
              "data_type": "FILE",
              "source": "/data/ast-run-harvester",
              "destination": "/data/tmp/ast-run-harvester"
            }
          ]
        }
      ]
    }
