# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{- include "apsviz-archiver.fullname" . }}-scripts"
data:
  rule_file.json: |-
    {
      "rule_definition_name": "APSViz archival rules",
      "rule_definition_version": "0.0.0",
      "description": "Log directory operations.",
      "rule_sets":
      [
        {
          "rule_set_name": "Archive rule set for log data.",
          "description": "DIRECTORY ops: Copy /data/logs/ -> /data/log-backups/, remove old dirs in /data/logs",
          "rules": [
            {
              "name": "Copy log directories",
              "description": "This rule copies directories of age >= 3 days from source to destination.",
              "query_criteria_type": "BY_AGE",
              "query_data_type": "INTEGER",
              "query_data_value": 3,
              "predicate_type": "GREATER_THAN_OR_EQUAL_TO",
              "action_type": "SWEEP_COPY",
              "data_type": "DIRECTORY",
              "source": "/data/logs/",
              "destination": "/data/log-backups/",
              "debug": false
            },
            {
              "name": "Remove log directories",
              "description": "This rule removes log directories  >= 14 days old.",
              "query_criteria_type": "BY_AGE",
              "query_data_type": "INTEGER",
              "query_data_value": 14,
              "predicate_type": "GREATER_THAN_OR_EQUAL_TO",
              "action_type": "SWEEP_REMOVE",
              "data_type": "DIRECTORY",
              "source": "/data/logs/",
              "destination": null,
              "debug": false
            }
          ]
        },
        {
          "rule_set_name": "Archive rule set for AST harvester data",
          "description": "Copy /data/ast-run-harvester files -> /data/ast-harvester-backups/",
          "rules": [
            {
              "name": "Copy AST harvester data directory",
              "description": "This rule copies files of a certain age from source to destination.",
              "query_criteria_type": "BY_AGE",
              "query_data_type": "INTEGER",
              "query_data_value": 1,
              "predicate_type": "GREATER_THAN_OR_EQUAL_TO",
              "action_type": "SWEEP_COPY",
              "data_type": "FILE",
              "source": "/data/ast-run-harvester/",
              "destination": "/data/ast-run-harvester-backups/",
              "debug": false
            }
          ]
        }
      ]
    }
