# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2024 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "geoserver.fullname" . }}
  labels:
    app: {{ template "geoserver.fullname" . }}
    chart: {{ template "geoserver.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- with .Values.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "geoserver.fullname" . }}
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      name: {{ template "geoserver.fullname" . }}
      labels:
        app: {{ template "geoserver.fullname" . }}
        chart: {{ template "geoserver.chart" . }}
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
        {{- with .Values.podLabels }}
        {{- tpl . $ | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- (tpl . $) | nindent 8 }}
        {{- end }}
    spec:
{{/*      {{ if .Values.isAWS }}*/}}
      securityContext:
{{/*        runAsUser: 1000*/}}
        fsGroup: 1000
{{/*      {{ end }}*/}}
      containers:
        - name: {{ template "geoserver.fullname" . }}
          image: {{ template "geoserver.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{/*          command: [ '/bin/sh' ]*/}}
{{/*          args: [ '-c', 'while true; do date; sleep 3600; done' ]*/}}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.enableJSONP }}
            - name: ENABLE_JSONP
              value: {{ .Values.enableJSONP | quote }}
            {{- end }}
            - name: PROXY_BASE_URL
              value: https://{{ .Values.ingress.host }}/geoserver
            {{- if .Values.geoserverDataDir }}
            - name: GEOSERVER_DATA_DIR
              value: {{ .Values.persistence.geoserverDataDir.mountPath | quote }}
            {{- end }}
            {{- if .Values.geowebcacheCacheDir }}
            - name: GEOWEBCACHE_CACHE_DIR
              value: {{ .Values.persistence.geowebCacheDir.mountPath | quote }}
            {{- end }}
            - name: GEOSERVER_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "geoserver.secretName" . }}
                  key: geoserver-user
            - name: GEOSERVER_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "geoserver.secretName" . }}
                  key: geoserver-password
            {{- with .Values.extraPodEnv }}
            {{- tpl . $ | nindent 12 }}
            {{- end }}
          ports:
            - name: http-geoserver
              containerPort: {{ .Values.service.target_port }}
              protocol: TCP
          {{- if .Values.probe }}
            {{- with .Values.probe }}
            {{- tpl . $ | nindent 10 }}
            {{- end }}
          {{- else }}
          {{- end }}
          volumeMounts:
            - mountPath: /usr/local/tomcat/conf/context.xml
              name: web-context-script
              subPath: "context.xml"
            - mountPath: /usr/local/tomcat/webapps/geoserver/WEB-INF/web.xml
              name: web-config-script
              subPath: "web.xml"
            {{- if .Values.persistence.geoserverDataDir.enabled }}
            - name: geoserver-data-dir
              mountPath: {{ .Values.persistence.geoserverDataDir.mountPath }}
            {{- end }}
            {{- if .Values.persistence.geowebCacheDir.enabled }}
            - name: geowebcache-cache-dir
              mountPath: {{ .Values.persistence.geowebCacheDir.mountPath }}
              subPath: {{ .Values.persistence.geowebCacheDir.subPath }}
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- (tpl . $) | nindent 12 }}
            {{- end }}
    {{- with .Values.nodeSelector}}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{- with .Values.extraPodSpec }}
      {{- tpl . $ | nindent 6 }}
      {{- end }}
      volumes:
        - name: web-context-script
          configMap:
            name: {{ .Values.deployPrefix }}web-context-script
            defaultMode: 0777
        - name: web-config-script
          configMap:
            name: {{ .Values.deployPrefix }}web-config-script
            defaultMode: 0777
        {{- with .Values.extraVolume }}
        {{- (tpl . $) | nindent 8 }}
        {{- end }}
{{- if and .Values.persistence.geoserverDataDir.enabled .Values.persistence.geoserverDataDir.existingClaim }}
        - name: geoserver-data-dir
          persistentVolumeClaim:
{{- with .Values.persistence.geoserverDataDir.existingClaim }}
            claimName: {{ tpl . $ }}
{{- end }}
{{- else if .Values.persistence.geoserverDataDir.enabled }}
        - name: geoserver-data-dir
          persistentVolumeClaim:
            claimName: {{ .Values.deployPrefix }}apsviz-geoserver-pvc
{{- else if not .Values.persistence.geoserverDataDir.enabled }}
        - name: geoserver-data-dir
          emptyDir: {}
{{- end }}

{{- if and .Values.persistence.geowebCacheDir.enabled .Values.persistence.geowebCacheDir.existingClaim }}
        - name: geowebcache-cache-dir
          persistentVolumeClaim:
{{- with .Values.persistence.geowebCacheDir.existingClaim }}
            claimName: {{ tpl . $ }}

{{- end }}
{{- else if .Values.persistence.geowebCacheDir.enabled }}
        - name: geowebcache-cache-dir
          persistentVolumeClaim:
            claimName: {{ template "geoserver.fullname" . }}-cache-dir
{{- else if not .Values.persistence.geowebCacheDir.enabled }}
        - name: geowebcache-cache-dir
          emptyDir: {}
{{- end }}
