# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

---
{{- if and .Values.persistence.geoserverDataDir.enabled (not .Values.persistence.geoserverDataDir.existingClaim) }}
{{ if .Values.isAWS }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: apsviz-geoserver-pv
spec:
  capacity:
    storage: {{ .Values.persistence.geoserverDataDir.size }}
  volumeMode: Filesystem
  accessModes:
  {{- range .Values.persistence.geoserverDataDir.accessModes }}
    - {{ . | quote }}
  {{- end }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.geoserverDataDir.storageClass }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.persistence.geoserverDataDir.efsHandle }}
{{ end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apsviz-geoserver-pvc
{{- with .Values.persistence.geoserverDataDir.annotations }}
  annotations:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
spec:
  accessModes:
  {{- range .Values.persistence.geoserverDataDir.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{ include "geoserver.geoserverDataDir.storageClass" . }}
  resources:
    requests:
      storage: {{ .Values.persistence.geoserverDataDir.size | quote }}

{{- end }}
{{- if and .Values.persistence.geowebcacheCacheDir.enabled (not .Values.persistence.geowebcacheCacheDir.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "geoserver.fullname" . }}-cache-dir
{{- with .Values.persistence.geowebcacheCacheDir.annotations }}
  annotations:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
spec:
  accessModes:
  {{- range .Values.persistence.geowebcacheCacheDir.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{ if .Values.isAWS }}
  storageClassName: "eds-sc"
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.persistence.geowebcacheCacheDir.size | quote }}
{{- end }}
