# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2024 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

# Default values for ast-run-harvester.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: containers.renci.org/eds/ast-run-harvester
  tag: "sometag"
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext:
  runAsUser: 1000
  fsGroup: 1000
  runAsGroup: 1000

volumes:
  name: some-vol
  claimName: some-pvc

run:
  crontab: "0 */6 * * *"
  daysBefore: -1

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: ""
  tls: []

resources:
  limits:
    ephemeral-storage: 256Mi
    memory: 1Gi
  requests:
    cpu: 1000m
    ephemeral-storage: 64Mi
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
