# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

FROM debian:stable-slim

RUN apt-get update && apt-get upgrade
RUN apt -y install postgresql
RUN apt -y install nano