# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

# Default values for apsviz-archiver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: containers.renci.org/eds/apsviz-archiver
  tag: "v0.0.5"
  pullPolicy: Always

run:
  crontab: "0 5 * * *"

system: 'Default'

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

