# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "ast-run-harvester.fullname" . }}-job
  labels:
    {{- include "ast-run-harvester.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.run.crontab }}"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3
      template:
        spec:
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          initContainers:
          - name: {{ .Chart.Name }}-cronjob
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            volumeMounts:
            - name:  {{ .Values.volumes.name }}
              mountPath: "/data"
            # command: ['/bin/sh', '-c', 'sleep 30']
            command: ['bash', './execute_run_harvest.sh', '/data/ast-run-harvester']
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
            env:
            - name: LOG_PATH
              valueFrom:
                secretKeyRef:
                  name: eds-keys
                  key: log-path
            - name: CONTRAILS_KEY
              valueFrom:
                secretKeyRef:
                  name: eds-keys
                  key: contrails-key
            - name: http_proxy
              valueFrom:
                secretKeyRef:
                  name: eds-keys
                  key: http-proxy-url
            - name: https_proxy
              valueFrom:
                secretKeyRef:
                  name: eds-keys
                  key: http-proxy-url
            - name: HTTP_PROXY
              valueFrom:
                secretKeyRef:
                  name: eds-keys
                  key: http-proxy-url
            - name: HTTPS_PROXY
              valueFrom:
                secretKeyRef:
                  name: eds-keys
                  key: http-proxy-url
          containers:
          - image: containers.renci.org/eds/apsviz-timeseriesdb-ingest:v0.0.10
            imagePullPolicy: Always
            name: apsviz-timeseriesdb-ingest-cronjob
            command: ['python', 'runIngest.py', '--harvestDir', '/data/ast-run-harvester/', '--ingestDir', '/data/ast-run-ingester/', '--dataType', 'obs', '--inputTask', 'SequenceIngest']
            volumeMounts:
            - name: {{ .Values.volumes.name }}
              mountPath: "/data"
            env:
              - name: APSVIZ_GAUGES_DB_DATABASE
                valueFrom:
                  secretKeyRef:
                    name: eds-keys
                    key: apsviz-gauges-database
              - name: APSVIZ_GAUGES_DB_ENGINE
                valueFrom:
                  secretKeyRef:
                    name: eds-keys
                    key: apsviz-gauges-engine
              - name: APSVIZ_GAUGES_DB_HOST
                valueFrom:
                  secretKeyRef:
                    name: eds-keys
                    key: apsviz-gauges-host
              - name: APSVIZ_GAUGES_DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: eds-keys
                    key: apsviz-gauges-password
              - name: APSVIZ_GAUGES_DB_PORT
                valueFrom:
                  secretKeyRef:
                    name: eds-keys
                    key: apsviz-gauges-port
              - name: APSVIZ_GAUGES_DB_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: eds-keys
                    key: apsviz-gauges-username
              - name: ASGS_DB_HOST
                valueFrom:
                  secretKeyRef:
                    name: eds-keys
                    key: asgs-host
              - name: ASGS_DB_PORT
                valueFrom:
                  secretKeyRef:
                    name: eds-keys
                    key: asgs-port
              - name: ASGS_DB_DATABASE
                valueFrom:
                  secretKeyRef:
                    name: eds-keys
                    key: asgs-database
              - name: ASGS_DB_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: eds-keys
                    key: asgs-username
              - name: ASGS_DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: eds-keys
                    key: asgs-password
              - name: AST_HARVESTER_DATA
                value: /data/ast-run-harvester
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
          restartPolicy: Never
          volumes:
            - name: {{ .Values.volumes.name }}
              persistentVolumeClaim:
                claimName: {{ .Values.volumes.claimName }}


