apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{- include "apsviz-archiver.fullname" . }}-scripts"
data:
  rule_file.json: |-
    {
      "rule_definition_name": "APSViz archival rules",
      "rule_definition_version": "0.0.0",
      "description": "Log directory operations.",
      "rule_sets":
      [
        {
          "rule_set_name": "Log operations rule set",
          "description": "Operations on log directories located in /data/logs.",
          "rules": [
            {
              "name": "Copy log directories",
              "description": "This rule copies directories of a certain age from source to destination.",
              "query_criteria_type": "BY_AGE",
              "query_data_type": "INTEGER",
              "query_data_value": 1,
              "predicate_type": "GREATER_THAN_OR_EQUAL_TO",
              "action_type": "SWEEP_COPY",
              "data_type": "DIRECTORY",
              "source": "/data/logs",
              "destination": "/data/tmp/archiver-test"
            },
            {
              "name": "Move log directories",
              "description": "This rule moves directories of a certain age from source to destination.",
              "query_criteria_type": "BY_AGE",
              "query_data_type": "INTEGER",
              "query_data_value": 1,
              "predicate_type": "GREATER_THAN_OR_EQUAL_TO",
              "action_type": "SWEEP_MOVE",
              "data_type": "DIRECTORY",
              "source": "/data/logs",
              "destination": "/data/tmp/archiver-test/old"
            }
          ]
        }
      ]
    }