# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2024 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sftpgo.fullname" . }}
  labels:
    {{- include "sftpgo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sftpgo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sftpgo.selectorLabels" . | nindent 8 }}
        type: sftp
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "sftpgo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: web
              containerPort: {{ .Values.service.target_port }}
              protocol: TCP
            - name: sftp
              containerPort: {{ .Values.service.connectPort }}
              protocol: TCP
          env:
            - name: SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN
              value: "1"
            - name: SFTPGO_DEFAULT_ADMIN_USERNAME
              value: {{ .Values.admin.username }}
            - name: SFTPGO_DEFAULT_ADMIN_PASSWORD
              value: {{ .Values.admin.password }}
            - name: SFTPGO_LOG_MAX_SIZE
              value: {{ .Values.volumes.sftp.maxLogSize | quote }}
            - name: SFTPGO_LOG_FILE_PATH
              value: {{ .Values.volumes.sftp.logFilePath | quote }}
          volumeMounts:
            - name: {{ .Values.volumes.sftp.name }}
              mountPath: {{ .Values.volumes.sftp.mountPoint }}

              {{- if not .Values.nfsVolumes }}
            - name: {{ .Values.volumes.thredds.name }}
              mountPath: {{ .Values.volumes.thredds.mountPoint }}
              {{- else }}
                {{- range $key, $value := .Values.nfsVolumes }}
            - name: {{ $value.name | quote }}
              mountPath: {{ $value.mountPath | quote }}
              readOnly: {{ $value.readOnly }}
                {{- end }}
              {{- end }}

          startupProbe:
            httpGet:
              path: /
              port: {{ .Values.service.target_port }}
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.target_port }}
            initialDelaySeconds: 1
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ .Values.volumes.sftp.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.sftp.claimName }}

        {{- if not .Values.nfsVolumes }}
        - name: {{ .Values.volumes.thredds.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.thredds.claimName }}
        {{- else }}
          {{- range $key, $value := .Values.nfsVolumes }}
        - name: {{ $value.name | quote }}
          nfs:
            path: {{ $value.path | quote }}
            server: {{ $value.server | quote}}
          {{- end }}
        {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
