{{ if .Values.volumes.sftp.create }}
{{ if .Values.isAWS }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: apsviz-sftpserver-pv
spec:
  capacity:
    storage: {{ .Values.volumes.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.volumes.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.volumes.storageClass }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.volumes.efsHandle }}
{{ end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.sftp.claimName }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - {{ .Values.volumes.accessMode }}
  {{ if .Values.isAWS }}
  storageClassName: {{ .Values.volumes.storageClass }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.volumes.size }}
{{ end }}
