# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

{{ if .Values.volumes.sftp.create }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.sftp.claimName }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - {{ .Values.volumes.sftp.accessMode }}
  {{ if .Values.isAWS }}
  storageClassName: {{ .Values.volumes.sftp.storageClass }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.volumes.sftp.size }}
{{ end }}

{{ if .Values.isAWS }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volumes.sftp.name }}
spec:
  capacity:
    storage: {{ .Values.volumes.sftp.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.volumes.sftp.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.volumes.sftp.storageClass }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.volumes.sftp.efsHandle }}
{{ end }}