# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sftpgo.fullname" . }}
  labels:
    {{- include "sftpgo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target_port }}
      protocol: TCP
      name: http
  selector:
    {{- include "sftpgo.selectorLabels" . | nindent 4 }}

{{ if .Values.networking.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sftpgo.fullname" . }}-connect
  labels:
    {{- include "sftpgo.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.networking.host }}
spec:
  type: {{ .Values.networking.type }}
  loadBalancerIP: {{ .Values.networking.loadbalancerIP }}
  ports:
  - name: {{ .Values.networking.name }}
    port: {{ .Values.networking.port }}
    protocol: TCP
  selector:
    {{- include "sftpgo.selectorLabels" . | nindent 4 }}

{{ if not .Values.isAWS }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: loadbalancer-port-for-sftp
spec:
  podSelector:
    matchLabels:
      type: sftp
  ingress:
  - from: []
    ports:
      - port: {{ .Values.networking.port }}
{{ end }}
{{ end }}
