apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{- include "apsviz-supervisor.fullname" . }}-scripts"
data:
  base_config.json: |-
    {
      "CLUSTER": {{ .Values.base_config.cluster | quote }},
      "NAMESPACE":  {{ .Values.base_config.namespace | quote }},
      "PVC_CLAIM":  {{ .Values.base_config.pvc_claim | quote }},
      "SECRETS_CLAIM":  {{ .Values.base_config.secrets_claim | quote }},
      "CREATE_SLEEP":  {{ .Values.base_config.create_sleep }}
    }
