apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apsviz-supervisor.fullname" . }}
  labels:
    {{- include "apsviz-supervisor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "apsviz-supervisor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "apsviz-supervisor.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "apsviz-supervisor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name:  {{ .Values.volumes.name }}
            mountPath: "/data"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: LOG_PATH
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: log-path
          - name: SSH_USERNAME
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: ssh-username
          - name: SSH_HOST
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: ssh-host
          - name: ASGS_DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: asgs-database
          - name: ASGS_DB_HOST
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: asgs-host
          - name: ASGS_DB_PORT
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: asgs-port
          - name: ASGS_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: asgs-username
          - name: ASGS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: asgs-password
          - name: GEOSERVER_USER
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: geo-username
          - name: GEOSERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: geo-password
          - name: GEOSERVER_URL
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: geo-host
          - name: GEOSERVER_WORKSPACE
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: geo-workspace
          - name: SLACK_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: slack-access-token
          - name: SLACK_CHANNEL
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: slack-channel
      volumes:
        - name: {{ .Values.volumes.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.claimname }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
