# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apsviz-supervisor.fullname" . }}
  labels:
    {{- include "apsviz-supervisor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "apsviz-supervisor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "apsviz-supervisor.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "apsviz-supervisor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name:  {{ .Values.volumes.name }}
            mountPath: "/data"
          - mountPath: /repo/APSVIZ-Supervisor/common/base_config.json
            name: "base-config-script"
            subPath: "base_config.json"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: LOG_PATH
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: log-path
          - name: ASGS_DB_HOST
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: asgs-host
          - name: ASGS_DB_PORT
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: asgs-port
          - name: ASGS_DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: asgs-database
          - name: ASGS_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: asgs-username
          - name: ASGS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: asgs-password
          - name: APSVIZ_DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: apsviz-database
          - name: APSVIZ_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: apsviz-username
          - name: APSVIZ_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: apsviz-password
          - name: SLACK_STATUS_TOKEN
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: slack-status-token
          - name: SLACK_STATUS_CHANNEL
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: slack-status-channel
          - name: SLACK_ISSUES_TOKEN
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: slack-issues-token
          - name: SLACK_ISSUES_CHANNEL
            valueFrom:
              secretKeyRef:
                name: eds-keys
                key: slack-issues-channel
          - name: SYSTEM
            value: {{ .Values.system  | quote }}
      volumes:
        - name: {{ .Values.volumes.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.claimName }}
        - name: base-config-script
          configMap:
            name: "{{- include "apsviz-supervisor.fullname" . }}-scripts"
            defaultMode: 0777

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
