{{ if .Values.volumes.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.claimname }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: basic
  resources:
    requests:
      storage: {{ .Values.volumes.size }}
{{ end }}