{{ if .Values.volumes.create }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eds-pvc
  annotations:
    # Allows users to uninstall the rsync-migrator helm chart afterwards
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi

{{ end }}