# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

{{ if .Values.logVolumes.create }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "asgs_message_handler.fullname" . }}-logs-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - {{ .Values.logVolumes.accessMode }}
  {{ if .Values.isAWS }}
  storageClassName: {{ .Values.logVolumes.storageClass }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.logVolumes.size }}
{{ end }}
