apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apsviz-terriamap.fullname" . }}
  labels:
    {{- include "apsviz-terriamap.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "apsviz-terriamap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "apsviz-terriamap.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "apsviz-terriamap.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: apsviz-terria-map-vol
              mountPath: /home/nru/usr/src/app/data
            - name: apsviz-fileserver-vol
              mountPath: /fileserver
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.ingress.https_proxy }}
          env:
            - name: HTTP_PROXY
              value: {{ .Values.ingress.https_proxy }}
          {{ end }}
      volumes:
        - name: apsviz-terria-map-vol
          persistentVolumeClaim:
            claimName: {{ include "apsviz-terriamap.fullname" . }}-pvc

        - name: apsviz-fileserver-vol
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.fileserverPvc }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
