# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2024 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apsviz-terriamap.fullname" . }}
  labels:
    {{- include "apsviz-terriamap.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "apsviz-terriamap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "apsviz-terriamap.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "apsviz-terriamap.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: apsviz-fileserver-vol
              mountPath: /fileserver
            - name:  {{ .Values.volumes.buildVolName }}
              mountPath: {{ .Values.volumes.buildMountPoint }}
            - name: "config-script"
              mountPath: {{ .Values.data.fileLocation }}/{{ .Values.data.fileName }}
              subPath: "{{ .Values.data.fileName }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.ingress.https_proxy }}
          env:
            - name: HTTP_PROXY
              value: {{ .Values.ingress.https_proxy }}
          {{ end }}
            - name: NODE_OPTIONS
              value: "--max_old_space_size=8192"
      volumes:
        - name: apsviz-fileserver-vol
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.fileserverPvc }}
        - name: {{ .Values.volumes.buildVolName }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.buildClaimName }}
        - name: config-script
          configMap:
            name: "{{- include "apsviz-terriamap.fullname" . }}-scripts"
            defaultMode: 0777
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
