# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apsviz-terriamap.fullname" . }}-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - ReadWriteOnce
  {{ if .Values.isAWS }}
  storageClassName: {{ .Values.storage.class }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
