apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apsviz-terriamap.name" . }}-pvc
spec:
  accessModes:
  - ReadWriteOnce
  {{ if .Values.isAWS }}
  storageClassName: eds-sc
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.storageSize }}
