# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

---
geoserverDataDir: /opt/mygeoserver/data_dir
geowebcacheCacheDir: /opt/mygeoserver/gwc

geoserverUser: superadmin
geoserverPassword: superpasswordlol

persistence:
  geoserverDataDir:
    storageClass: "default"
    mountPath: /opt/mygeoserver/data_dir
  geowebcacheCacheDir:
    storageClass: "default"
    mountPath: /opt/mygeoserver/gwc

ingress:
  enabled: true
  host: geoserver.test
  pathType: "ImplementationSpecific"
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
  tls:
    enabled: true
    secretName: geoserver-tls
