apiVersion: v1
kind: Secret
metadata:
  name: {{ include "asgs-rabbitmq.fullname" . }}-secrets
type: Opaque
data:
  queue_user: {{ .Values.secrets.queueUser | b64enc | quote }}
  queue_pw: {{ .Values.secrets.queuePassword | b64enc | quote }}
  queue_admin_pw: {{ .Values.secrets.queueAdminPassword | b64enc | quote }}