apiVersion: v1
kind: Service
metadata:
  name: {{ include "asgs-rabbitmq.fullname" . }}
  labels:
    {{- include "asgs-rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.secrets.webPort }}
      targetPort: {{ .Values.secrets.webPort }}
      protocol: TCP
      name: rbtmq-http-prt
    - port: {{ .Values.secrets.amqpPort }}
      targetPort: {{ .Values.secrets.amqpPort }}
      protocol: TCP
      name: rbtmq-amqp-prt
  selector:
    {{- include "asgs-rabbitmq.selectorLabels" . | nindent 4 }}
