# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

{{ if .Values.volumes.create }}
{{ if .Values.isAWS }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-volume-pv
spec:
  capacity:
    storage: {{ .Values.volumes.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.volumes.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.volumes.storageClass }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.volumes.efsHandle }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-volume-pv
spec:
  capacity:
    storage: {{ .Values.volumes.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.volumes.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.volumes.storageClass }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.volumes.efsHandle }}
{{ end }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apsviz-timeseries-web.name" . }}-static-volume
spec:
  accessModes:
  - {{ .Values.volumes.accessMode }}
  {{ if .Values.isAWS }}
  storageClassName: {{ .Values.volumes.storageClass }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.volumes.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apsviz-timeseries-web.name" . }}-media-volume
spec:
  accessModes:
  - {{ .Values.volumes.accessMode }}
  {{ if .Values.isAWS }}
  storageClassName: {{ .Values.volumes.storageClass }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.volumes.size }}
{{ end }}
