# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2024 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apsviz-thredds.fullname" . }}
  labels:
    {{- include "apsviz-thredds.labels" . | nindent 4 }}
spec:
  {{ if .Values.isAWS }}
  replicas: {{ .Values.replicaCount }}
  {{ end }}

  selector:
    matchLabels:
      {{- include "apsviz-thredds.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "apsviz-thredds.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "apsviz-thredds.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: THREDDS_XMX_SIZE
              value: {{ .Values.THREDDS.THREDDS_XMX_SIZE | quote }}
            - name: THREDDS_XMS_SIZE
              value: {{ .Values.THREDDS.THREDDS_XMS_SIZE | quote}}
          ports:
            - name: http
              containerPort: {{ .Values.service.target_port }}
              protocol: TCP
          volumeMounts:
            - name: {{ .Values.logVolumes.claimName }}
              mountPath: {{ .Values.logVolumes.mountPoint }}

            - name: tds-config-script
              mountPath: {{ .Values.tomcatCatalinaHome }}/conf/tomcat-users.xml
              subPath: "tomcat-users.xml"

            - name: tds-config-script
              mountPath: {{ .Values.tomcatCatalinaHome }}/conf/server.xml
              subPath: "server.xml"

            {{- if ne .Values.configMapType.configMapName "none" -}}
              {{ $catalina_home := .Values.tomcatCatalinaHome -}}
              {{ $config_map := .Values.configMapType.configMapName -}}

              {{- range $key, $value := .Values.configMapFiles }}
            - name: tds-config-script
              mountPath: {{ $catalina_home }}{{ $value.mountPath }}{{ $value.subPath }}
              subPath: {{ $value.subPath | quote }}
              {{- end }}
            {{- end }}

            {{- if eq .Values.nfsVolumeEnable false }}
            - name: {{ .Values.dataVolumes.claimName }}
              mountPath: {{ .Values.dataVolumes.mountPoint }}
            {{- else }}
              {{- range $key, $value := .Values.nfsVolumes }}
            - name: {{ $value.name | quote }}
              mountPath: {{ $value.mountPath | quote }}
              {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ .Values.logVolumes.claimName }}
          persistentVolumeClaim:
            claimName: {{ include "apsviz-thredds.fullname" . }}-logs-pvc

        {{- if ne .Values.configMapType.configMapName "none" }}
        - name: tds-config-script
          configMap:
            name: {{ .Values.configMapType.configMapName }}
            defaultMode: 0777
        {{ end }}

        {{- if eq .Values.nfsVolumeEnable false }}
        - name: {{ .Values.dataVolumes.claimName }}
          persistentVolumeClaim:
            claimName: {{ include "apsviz-thredds.fullname" . }}-data-pvc
        {{- else }}
          {{- range $key, $value := .Values.nfsVolumes }}
        - name: {{ $value.name | quote }}
          nfs:
            path: {{ $value.path | quote }}
            server: {{ $value.server | quote}}
            readOnly: true
          {{- end }}
        {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
