# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apsviz-thredds.fullname" . }}
  labels:
    {{- include "apsviz-thredds.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "apsviz-thredds.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "apsviz-thredds.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "apsviz-thredds.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: THREDDS_XMX_SIZE
              value: "6G"
            - name: THREDDS_XMS_SIZE
              value: "4G"
            - name: TDS_CONTENT_ROOT_PATH
              value: /home/nru/tomcat/content
          ports:
            - name: http
              containerPort: {{ .Values.service.target_port }}
              protocol: TCP
          volumeMounts:
            - name: "javaopt-config-script"
              mountPath: /home/nru/tomcat/bin/javaopts.sh
              subPath: "javaopts.sh"
            - name: {{ .Values.logVolumes.claimName }}
              mountPath: {{ .Values.logVolumes.mountPoint }}
            {{- if not .Values.nfsVolumes }}
            - name: {{ .Values.dataVolumes.claimName }}
              mountPath: {{ .Values.dataVolumes.mountPoint }}
            {{- else }}
            - name: {{ .Values.nfsVolumes.name1 }}
              mountPath: {{ .Values.nfsVolumes.mountPath1 }}
            - name: {{ .Values.nfsVolumes.name2 }}
              mountPath: {{ .Values.nfsVolumes.mountPath2 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: javaopt-config-script
          configMap:
            name: "{{- include "apsviz-thredds.fullname" . }}-scripts"
            defaultMode: 0777
        - name: {{ .Values.logVolumes.claimName }}
          persistentVolumeClaim:
            claimName: {{ include "apsviz-thredds.fullname" . }}-logs-pvc
        {{- if not .Values.nfsVolumes }}
        - name: {{ .Values.dataVolumes.claimName }}
          persistentVolumeClaim:
            claimName: {{ include "apsviz-thredds.fullname" . }}-data-pvc
        {{- else }}
        {{- with .Values.nfsVolumes }}
        - name: {{ .name1 }}
          nfs:
            server: {{ .server }}
            path: {{ .path1 }}
        - name: {{ .name2 }}
          nfs:
            server: {{ .server }}
            path: {{ .path2 }}
        {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
