# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

{{ if .Values.logVolumes.create }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apsviz-thredds.fullname" . }}-logs-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - {{ .Values.logVolumes.accessMode }}
  {{ if .Values.isAWS }}
  storageClassName: {{ .Values.logVolumes.storageClass }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.logVolumes.size }}
{{ end }}

{{ if .Values.dataVolumes.create }}
{{ if .Values.isAWS }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.dataVolumes.name }}
spec:
  capacity:
    storage: {{ .Values.dataVolumes.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.dataVolumes.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.dataVolumes.storageClass }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.dataVolumes.efsHandle }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.logVolumes.name }}
spec:
  capacity:
    storage: {{ .Values.logVolumes.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.dataVolumes.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.logVolumes.storageClass }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.logVolumes.efsHandle }}
{{ end }}
{{- if not .Values.nfsVolumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apsviz-thredds.fullname" . }}-data-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - {{ .Values.dataVolumes.accessMode }}
  {{ if .Values.isAWS }}
  storageClassName: {{ .Values.dataVolumes.storageClass }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.dataVolumes.size }}
{{ end }}
{{ end }}
