apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apsviz-thredds.name" . }}-ncfs-pvc
spec:
  accessModes:
  - ReadWriteOnce
  {{ if .Values.isAWS }}
  storageClassName: {{ .Values.storage.class }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apsviz-thredds.name" . }}-reanalysis-pvc
spec:
  accessModes:
  - ReadWriteOnce
  {{ if .Values.isAWS }}
  storageClassName: {{ .Values.storage.class }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}