apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apsviz-thredds.name" . }}-ncfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storageSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apsviz-thredds.name" . }}-reanalysis-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storageSize }}