apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apsviz-thredds.name" . }}-ncfs-pvc
spec:
  accessModes:
  - ReadWriteOnce
  {{ if .Values.isAWS }}
  storageClassName: eds-sc
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.storageSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apsviz-thredds.name" . }}-reanalysis-pvc
spec:
  accessModes:
  - ReadWriteOnce
  {{ if .Values.isAWS }}
  storageClassName: eds-sc
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.storageSize }}