apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apsviz-thredds.fullname" . }}-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - ReadWriteMany
  {{ if .Values.isAWS }}
  storageClassName: {{ .Values.storage.class }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
