# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{- include "apsviz-thredds.fullname" . }}-scripts"
data:
  aps2023.xml: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<catalog name=\"APS/NCFS/RENCI\"\n
    \       xmlns=\"http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0\"\n
    \       xmlns:xlink=\"http://www.w3.org/1999/xlink\">\n\n        <service name=\"all\"
    base=\"\" serviceType=\"compound\">\n           <service name=\"odap\" serviceType=\"OpenDAP\"
    base=\"/thredds/dodsC/\" />\n           <!--service name=\"dap4\" serviceType=\"DAP4\"
    base=\"/thredds/dap4/\" /-->\n           <service name=\"http\" serviceType=\"HTTPServer\"
    base=\"/thredds/fileServer/\" />\n           <service name=\"ncml\" serviceType=\"NCML\"
    base=\"/thredds/ncml/\" />\n        </service>\n\n\t<datasetScan\n\t    name=\"APS-2023\"\n\t
    \   ID=\"APS-2023\"\n\t    path=\"2023\"\n\t    location=\"/projects/ncfs/opendap/data/2023\">\n\n\t
    \   <metadata inherited=\"true\">\n\t\t<serviceName>all</serviceName>\n\t\t<documentation
    type=\"summary\"> APS Results for 2023 </documentation>\n\t    </metadata>\n            <filesSort
    increasing=\"false\" />\n\t    <filter>\n\t\t<include wildcard=\"*\"/>\n\t    </filter>\n\n\t</datasetScan>\n\n</catalog>\n\n"

  asgs2021.xml: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<catalog name=\"ASGS/NCFS/RENCI\"\n
    \       xmlns=\"http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0\"\n
    \       xmlns:xlink=\"http://www.w3.org/1999/xlink\">\n\n        <service name=\"all\"
    base=\"\" serviceType=\"compound\">\n           <service name=\"odap\" serviceType=\"OpenDAP\"
    base=\"/thredds/dodsC/\" />\n           <service name=\"dap4\" serviceType=\"DAP4\"
    base=\"/thredds/dap4/\" />\n           <service name=\"http\" serviceType=\"HTTPServer\"
    base=\"/thredds/fileServer/\" />\n           <service name=\"ncml\" serviceType=\"NCML\"
    base=\"/thredds/ncml/\" />\n        </service>\n\n\t<datasetScan\n\t    name=\"ASGS-2021\"\n\t
    \   ID=\"ASGS-2021\"\n\t    path=\"2021\"\n\t    location=\"/projects/ncfs/opendap/data/2021\">\n\n\t
    \   <metadata inherited=\"true\">\n\t\t<serviceName>all</serviceName>\n\t\t<documentation
    type=\"summary\"> ASGS Results for 2021 </documentation>\n\t    </metadata>\n\n\t
    \   <filter>\n\t\t<include wildcard=\"*\"/>\n\t    </filter>\n\t</datasetScan>\n\n\n</catalog>\n\n"

  asgs2022.xml: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<catalog name=\"ASGS/NCFS/RENCI\"\n
    \       xmlns=\"http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0\"\n
    \       xmlns:xlink=\"http://www.w3.org/1999/xlink\">\n\n        <service name=\"all\"
    base=\"\" serviceType=\"compound\">\n           <service name=\"odap\" serviceType=\"OpenDAP\"
    base=\"/thredds/dodsC/\" />\n           <service name=\"dap4\" serviceType=\"DAP4\"
    base=\"/thredds/dap4/\" />\n           <service name=\"http\" serviceType=\"HTTPServer\"
    base=\"/thredds/fileServer/\" />\n           <service name=\"ncml\" serviceType=\"NCML\"
    base=\"/thredds/ncml/\" />\n        </service>\n\n\t<datasetScan\n\t    name=\"ASGS-2022\"\n\t
    \   ID=\"ASGS-2022\"\n\t    path=\"2022\"\n\t    location=\"/projects/ncfs/opendap/data/2022\">\n\n\t
    \   <metadata inherited=\"true\">\n\t\t<serviceName>all</serviceName>\n\t\t<documentation
    type=\"summary\"> ASGS Results for 2022 </documentation>\n\t    </metadata>\n\n\t
    \   <filter>\n\t\t<include wildcard=\"*\"/>\n\t    </filter>\n\t</datasetScan>\n\n\n</catalog>\n\n"

  catalog.xml: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<catalog name=\"APS Thredds
    Data Server\"\n        xmlns=\"http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0\"\n
    \       xmlns:xlink=\"http://www.w3.org/1999/xlink\">\n\n  <service name=\"all\"
    base=\"\" serviceType=\"compound\">\n    <service name=\"odap\" serviceType=\"OpenDAP\"
    base=\"/thredds/dodsC/\" />\n    <!--service name=\"dap4\" serviceType=\"DAP4\"
    base=\"/thredds/dap4/\" /-->\n    <service name=\"http\" serviceType=\"HTTPServer\"
    base=\"/thredds/fileServer/\" />\n  </service>\n\n  <dataset name=\"RENCI APS
    THREDDS Catalogs\">\n    \n     <datasetScan\n       name=\"NCFS_CURRENT_TROPICAL\"\n
    \      ID=\"NCFS_CURRENT_TROPICAL\"\n       path=\"NCFS_CURRENT_TROPICAL\"\n       location=\"/projects/ncfs/opendap/data/NCFS_CURRENT_TROPICAL\">\n\n
    \      <metadata inherited=\"true\">\n          <serviceName>all</serviceName>\n
    \         <documentation type=\"summary\"> NCFS CURRENT TROPICAL Results </documentation>\n
    \      </metadata>\n\n       <filter>\n          <include wildcard=\"*\"/>\n       </filter>\n\n
    \    </datasetScan>\n\n    <datasetScan\n       name=\"NCFS_CURRENT_SYNOPTIC\"\n
    \      ID=\"NCFS_CURRENT_SYNOPTIC\"\n       path=\"NCFS_CURRENT_SYNOPTIC\"\n       location=\"/projects/ncfs/opendap/data/NCFS_CURRENT_DAILY\">\n\n
    \      <metadata inherited=\"true\">\n          <serviceName>all</serviceName>\n
    \         <documentation type=\"summary\"> NCFS CURRENT SYNOPTIC Results </documentation>\n
    \      </metadata>\n\n       <filter>\n          <include wildcard=\"*\"/>\n       </filter>\n\n
    \   </datasetScan>\n\n    <catalogRef xlink:href=\"aps2023.xml\"                 xlink:title=\"RENCI
    APS 2023\"                   name=\"\"/>\n    <catalogRef xlink:href=\"asgs2022.xml\"
    \               xlink:title=\"RENCI APS 2022\"                   name=\"\"/>\n
    \   <catalogRef xlink:href=\"asgs2021.xml\"                xlink:title=\"RENCI
    APS 2021\"                   name=\"\"/>\n    <!--catalogRef xlink:href=\"asgs2019.xml\"
    \               xlink:title=\"RENCI APS 2019\"                   name=\"\"/-->\n
    \   <!--catalogRef xlink:href=\"asgs2018.xml\"                xlink:title=\"RENCI
    APS 2018\"                   name=\"\"/-->\n  </dataset>\n\n     <dataset name=\"RENCI
    Reanalysis Catalogs\">\n\t  <catalogRef xlink:href=\"Reanalysis.xml\"  xlink:title=\"RENCI
    Reanalysis\"  name=\"\"/>\n     </dataset>\n\n\n  <!--dataset name=\"test\"-->\n
    \   <!--catalogRef xlink:href=\"test.xml\"  xlink:title=\"test\"  name=\"\"/-->\n
    \ <!--/dataset-->\n\n</catalog>\n"

  Reanalysis.xml: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<catalog name=\"Coastal
    Reanalysis\"\n         xmlns=\"http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0\"\n
    \        xmlns:xlink=\"http://www.w3.org/1999/xlink\">\n<!--\n  <contributor role=\"data
    manager\">John Smith</contributor>\n  <keyword>Atmospheric Chemistry</keyword>\n
    \ <publisher>\n    <long_name vocabulary=\"DIF\">Community Data Portal, National
    Center for Atmospheric Research, University Corporation for Atmospheric Research</long_name>\n
    \   <contact url=\"http://dataportal.ucar.edu\" email=\"cdp@ucar.edu\"/>\n  </publisher>\n-->\n\n
    \   <service name=\"ThisAll\" base=\"\" serviceType=\"compound\">\n        <service
    name=\"odap\" serviceType=\"OpenDAP\" base=\"/thredds/dodsC/\" />\n        <!--service
    name=\"dap4\" serviceType=\"DAP4\" base=\"/thredds/dap4/\" /-->\n        <service
    name=\"http\" serviceType=\"HTTPServer\" base=\"/thredds/fileServer/\" />\n        <!--service
    name=\"wcs\" serviceType=\"WCS\" base=\"/thredds/wcs/\" /-->\n        <!--service
    name=\"wms\" serviceType=\"WMS\" base=\"/thredds/wms/\" /-->\n        <!--service
    name=\"ncss\" serviceType=\"NetcdfSubset\" base=\"/thredds/ncss/\" /-->\n        <!--service
    name=\"iso\" serviceType=\"ISO\" base=\"/thredds/iso/\" /-->\n        <service
    name=\"ncml\" serviceType=\"NCML\" base=\"/thredds/ncml/\" />\n        <!--service
    name=\"uddc\" serviceType=\"UDDC\" base=\"/thredds/uddc/\" /-->\n    </service>\n\n
    \   <datasetScan \n        name=\"ADCIRC\" \n        ID=\"ADCIRC\" \n        path=\"ReanalysisV2/ADCIRC\"
    \n\t    location=\"/projects/reanalysis/ADCIRC/ERA5/hsofs.V2\">\n\n        <metadata
    inherited=\"true\">\n\t    <serviceName>all</serviceName>\n            <authority>renci.org</authority>\n
    \           <dataType>GRID</dataType>\n            <documentation> Reanalysis
    ADCIRC solutions.  </documentation>\n        </metadata>\n        <filter>\n\t\t<!--include
    wildcard=\"*\"/-->\n\t\t<!--include wildcard=\"fort.15\"/-->\n\t\t<!--include
    wildcard=\"*.nc\"/-->\n\t\t<!--exclude wildcard=\"fort.22*\"/-->  \n\t\t<!--exclude
    wildcard=\"*.sh\"/ -->\n\t\t<exclude wildcard=\"run.*\"/>\n\t\t<exclude wildcard=\"fort.??\"/>\n\t\t<exclude
    wildcard=\"initiallydry.63.nc\"/>\n\t\t<exclude wildcard=\"inundationtime.63.nc\"/>\n\t\t<exclude
    wildcard=\"endrisinginun.63.nc\"/>\n\t\t<exclude wildcard=\"everdried.63.nc\"/>\n\t\t<exclude
    wildcard=\"adcirc.log\"/>\n\t\t<exclude wildcard=\"swaninit\"/>\n\t\t<exclude
    wildcard=\"submit.*\"/>\n\t\t<exclude wildcard=\"temp.1\"/>\n\t\t<exclude wildcard=\"tide_fac.out\"/>\n\t\t<exclude
    wildcard=\"slurm*\"/>\n\t\t<exclude wildcard=\"*.sh\"/>\n\t\t<exclude wildcard=\"*~\"/>\n\t\t<exclude
    wildcard=\"*.py\"/>\n\t\t<exclude wildcard=\"README\"/>\n\t\t<exclude wildcard=\"*.txt\"/>\n\t\t<exclude
    wildcard=\".gitignore*\"/>\n\t\t<exclude wildcard=\"Grids\" atomic=\"false\" collection=\"true\"
    />\n\t\t<exclude wildcard=\"bin\" atomic=\"false\" collection=\"true\" />\n\t\t<exclude
    wildcard=\"configs\" atomic=\"false\" collection=\"true\" />\n\t\t<exclude wildcard=\"common\"
    atomic=\"false\" collection=\"true\" />\n\t\t<exclude wildcard=\"Tides\" atomic=\"false\"
    collection=\"true\" />\n\t\t<exclude wildcard=\"TracksToRun\" atomic=\"false\"
    collection=\"true\" />\n\t\t<exclude wildcard=\"ec95d*\" atomic=\"false\" collection=\"true\"
    />\n\t\t<exclude wildcard=\"PE*\" atomic=\"false\" collection=\"true\" />\n\t\t<exclude
    wildcard=\".git*\" atomic=\"false\" collection=\"true\" />\n\t\t</filter>\n        <sort>\n
    \            <lexigraphicByName increasing=\"true\"/>\n        </sort>\n    </datasetScan>\n\n<!--/dataset-->\n\n</catalog>\n"

  threddsConfig.xml: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<threddsConfig>\n\n
    \ <!-- all options are commented out in standard install - meaning use default
    values -->\n  <!-- see http://www.unidata.ucar.edu/projects/THREDDS/tech/reference/ThreddsConfigXMLFile.html
    -->\n  <serverInformation>\n    <name>THREDDS</name>\n    <logoUrl>/thredds/renci-logo.png</logoUrl>\n
    \   <logoAltText>THREDDS</logoAltText>\n\n    <abstract>Scientific Data</abstract>\n
    \   <keywords>meteorology, atmosphere, climate, ocean, earth science</keywords>\n\n
    \   <contact>\n      <name>Brian Blanton</name>\n      <organization>RENCI</organization>\n
    \     <email>bblanton@renci.org</email>\n      <!--phone></phone-->\n    </contact>\n
    \   <hostInstitution>\n      <name>RENCI</name>\n      <webSite>https://www.renci.org/</webSite>\n
    \     <logoUrl>/thredds/renci-logo.png</logoUrl>\n      <logoAltText>RENCI</logoAltText>\n
    \   </hostInstitution>\n  </serverInformation>\n\n  <!--\n  The <catalogRoot>
    element:\n  For catalogs you don't want visible from the /thredds/catalog.xml
    chain\n  of catalogs, you can use catalogRoot elements. Each catalog root config\n
    \ catalog is crawled and used in configuring the TDS.\n\n  <catalogRoot>myExtraCatalog.xml</catalogRoot>\n
    \ <catalogRoot>myOtherExtraCatalog.xml</catalogRoot>\n  -->\n\n  <!--\n   * Setup
    for generated HTML pages.\n   *\n   * NOTE: URLs may be absolute or relative,
    relative URLs must be relative\n   * to the webapp URL, i.e., http://server:port/thredds/.\n
    \   -->\n  <htmlSetup>\n    <!--\n     * CSS documents used in generated HTML
    pages.\n     * The CSS document given in the \"catalogCssUrl\" element is used
    for all pages\n     * that are HTML catalog views. The CSS document given in the
    \"standardCssUrl\"\n     * element is used in all other generated HTML pages.\n
    \    * -->\n    <standardCssUrl>tds.css</standardCssUrl>\n    <catalogCssUrl>tdsCat.css</catalogCssUrl>\n
    \   <openDapCssUrl>tdsDap.css</openDapCssUrl>\n\n    <!--\n     * The Google Analytics
    Tracking code you would like to use for the\n     * webpages associated with THREDDS.
    This will not track WMS or DAP\n     * requests for data, only browsing the catalog.\n
    \   -->\n    <googleTrackingCode></googleTrackingCode>\n\n  </htmlSetup>\n\n  <!--\n
    \   The <TdsUpdateConfig> element controls if and how the TDS checks\n    for
    updates. The default is for the TDS to check for the current\n    stable and development
    release versions, and to log that information\n    in the TDS serverStartup.log
    file as INFO entries.\n\n  <TdsUpdateConfig>\n     <logVersionInfo>true</logVersionInfo>\n
    \ </TdsUpdateConfig>\n  -->\n\n  <!--\n   The <CORS> element controls Cross-Origin
    Resource Sharing (CORS).\n   CORS is a way to allow a website (such as THREDDS)
    to open up access\n   to resources to web pages and applications running on a
    different domain.\n   One example would be allowing a web-application to use fonts
    from\n   a separate host. For TDS, this can allow a javascript app running on
    a\n   different site to access data on a THREDDS server.\n   For more information
    see: https://en.wikipedia.org/wiki/Cross-origin_resource_sharing\n   The elements
    below represent defaults. Only the <enabled> tag is required\n   to enable CORS.
    The default allowed origin is '*', which allows sharing\n   to any domain.\n  -->\n
    \ <CORS>\n    <enabled>true</enabled>\n    <maxAge>1728000</maxAge>\n    <allowedMethods>GET</allowedMethods>\n
    \   <allowedHeaders>Authorization</allowedHeaders>\n    <allowedOrigin>*</allowedOrigin>\n
    \ </CORS>\n\n  <!--\n   The <CatalogServices> element:\n   - Services on local
    TDS served catalogs are always on.\n   - Services on remote catalogs are set with
    the allowRemote element\n   below. They are off by default (recommended).\n   -->\n
    \ <CatalogServices>\n    <allowRemote>false</allowRemote>\n  </CatalogServices>\n\n
    \ <!--\n  Configuring the CDM (netcdf-java library)\n  see http://www.unidata.ucar.edu/software/netcdf-java/reference/RuntimeLoading.html\n\n
    \ <nj22Config>\n    <ioServiceProvider class=\"edu.univ.ny.stuff.FooFiles\"/>\n
    \   <coordSysBuilder convention=\"foo\" class=\"test.Foo\"/>\n    <coordTransBuilder
    name=\"atmos_ln_sigma_coordinates\" type=\"vertical\" class=\"my.stuff.atmosSigmaLog\"/>\n
    \   <typedDatasetFactory datatype=\"Point\" class=\"gov.noaa.obscure.file.Flabulate\"/>\n
    \ </nj22Config>\n  -->\n\n  <!--\n  CDM uses the DiskCache directory to store
    temporary files, like uncompressed files.\n  <DiskCache>\n    <alwaysUse>false</alwaysUse>\n
    \   <scour>1 hour</scour>\n    <maxSize>1 Gb</maxSize>\n  </DiskCache>\n  -->\n\n
    \ <!--\n  Caching open NetcdfFile objects.\n  default is to allow 50 - 100 open
    files, cleanup every 11 minutes\n  <NetcdfFileCache>\n    <minFiles>50</minFiles>\n
    \   <maxFiles>100</maxFiles>\n    <scour>11 min</scour>\n  </NetcdfFileCache>\n
    \ -->\n\n  <!--\n  The <HTTPFileCache> element:\n  allow 10 - 20 open datasets,
    cleanup every 17 minutes\n  used by HTTP Range requests.\n  <HTTPFileCache>\n
    \   <minFiles>10</minFiles>\n    <maxFiles>20</maxFiles>\n    <scour>17 min</scour>\n
    \ </HTTPFileCache>\n  -->\n\n  <!--\n  Writing GRIB indexes.\n  <GribIndexing>\n
    \   <setExtendIndex>false</setExtendIndex>\n    <alwaysUseCache>false</alwaysUseCache>\n
    \ </GribIndexing>\n  -->\n\n  <!--\n  Persist joinNew aggregations to named directory.
    scour every 24 hours, delete stuff older than 90 days\n  <AggregationCache>\n
    \   <scour>24 hours</scour>\n    <maxAge>90 days</maxAge>\n  </AggregationCache>\n
    \ -->\n\n  <!--\n  How to choose the template dataset for an aggregation. latest,
    random, or penultimate\n  <Aggregation>\n    <typicalDataset>penultimate</typicalDataset>\n
    \ </Aggregation>\n  -->\n\n  <!--\n  The Netcdf Subset Service is off by default.\n
    \ -->\n  <NetcdfSubsetService>\n    <allow>true</allow>\n    <scour>10 min</scour>\n
    \   <maxAge>-1 min</maxAge>\n  </NetcdfSubsetService>\n\n  <!--\n  <Opendap>\n
    \   <ascLimit>50</ascLimit>\n    <binLimit>500</binLimit>\n    <serverVersion>opendap/3.7</serverVersion>\n
    \ </Opendap>\n    -->\n\n  <!--\n  The WCS Service is off by default.\n  Also,
    off by default (and encouraged) is operating on a remote dataset.\n  -->\n  <WCS>\n
    \   <allow>true</allow>\n    <allowRemote>false</allowRemote>\n    <scour>15 min</scour>\n
    \   <maxAge>30 min</maxAge>\n  </WCS>\n\n  <WMS>\n    <allow>true</allow>\n    <allowRemote>false</allowRemote>\n
    \   <maxImageWidth>2048</maxImageWidth>\n    <maxImageHeight>2048</maxImageHeight>\n
    \ </WMS>\n\n  <NCISO>\n    <ncmlAllow>true</ncmlAllow>\n    <uddcAllow>true</uddcAllow>\n
    \   <isoAllow>true</isoAllow>\n  </NCISO>\n\n  <!-- To enable ncSOS, uncomment
    and set to true\n  <NCSOS>\n    <allow>false</allow>\n  </NCSOS>\n  -->\n  \n
    \ <!-- CatalogGen service is off by default.\n  <CatalogGen>\n    <allow>false</allow>\n
    \ </CatalogGen>\n   -->\n\n  <!-- DLwriter service is off by default.\n       As
    is support for operating on remote catalogs.\n  <DLwriter>\n    <allow>false</allow>\n
    \   <allowRemote>false</allowRemote>\n  </DLwriter>\n   -->\n\n  <!-- DqcService
    is off by default.\n  <DqcService>\n    <allow>false</allow>\n  </DqcService>\n
    \  -->\n\n  <!--\n   Link to a Viewer application on the HTML page:\n   <Viewer>my.package.MyViewer</Viewer>\n
    \  -->\n\n   <!--\n   Add a DataSource - essentially an IOSP with access to Servlet
    request parameters\n   <datasetSource>my.package.DatsetSourceImpl</datasetSource>\n
    \  -->\n\n  <!--\n   set FeatureCollection logging\n  <FeatureCollection>\n     <RollingFileAppender>\n
    \      <MaxFileSize>1 MB</MaxFileSize>\n       <MaxBackups>5</MaxBackups>\n       <Level>INFO</Level>\n
    \    </RollingFileAppender>\n  </FeatureCollection>\n  -->\n\n\n</threddsConfig>\n"

  tomcat-users.xml: |-
    <?xml version='1.0' encoding='utf-8'?>
    <tomcat-users xmlns="http://tomcat.apache.org/xml"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://tomcat.apache.org/xml tomcat-users.xsd"
                  version="1.0">

      <role rolename="tdsConfig" description="can change THREDDS configuration files"/>
      <role rolename="tdsMonitor" description="can monitor log files with tdsMonitor program"/>
      <role rolename="tdsTrigger" description="can trigger feature collections, eg from tdm"/>

    {{- range $key, $value := .Values.tomcatUsers }}
      <user username={{ $value.name | quote }} password={{ $value.password | quote }} roles={{ $value.roles | quote }} />
    {{- end }}
    </tomcat-users>