# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{- include "apsviz-thredds.fullname" . }}-scripts"
data:
  tomcat-users.xml: |-
    <?xml version='1.0' encoding='utf-8'?>
    <tomcat-users xmlns="https://tomcat.apache.org/xml"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="https://tomcat.apache.org/xml tomcat-users.xsd"
                  version="1.0">

      <role rolename="tdsConfig" description="can change THREDDS configuration files"/>
      <role rolename="tdsMonitor" description="can monitor log files with tdsMonitor program"/>
      <role rolename="tdsTrigger" description="can trigger feature collections, eg from tdm"/>

    {{- range $key, $value := .Values.tomcatUsers }}
      <user username={{ $value.name | quote }} password={{ $value.password | quote }} roles={{ $value.roles | quote }} />
    {{- end }}
    </tomcat-users>
